name: DNS Backup
on: 
  schedule:
    - cron: "0 17 7 * *"
  workflow_dispatch:
  
jobs:
  dns-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%b-%Y')" >> $GITHUB_OUTPUT
      
      - name: Make script executable
        run: chmod +x scripts/dns-backup.sh
      
      - name: Fetch DNS Records
        run: ./scripts/dns-backup.sh uditmittal.com
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dns-records-uditmittal.com.txt
          tag_name: ${{ steps.date.outputs.date }}
